### ISSUE TITLE
YO BRIAN - I'M CHECKING THE DOCS 

### ISSUE THREAD

**Issue by spencerwyckoff** [GroupOneCheckers/Checkers_RB#17]
and we're not getting an ID returned and the game board is flipped - Player 1 on top as opposed to bottom.

**Comment by kingcons** [comment]
trololololololol @brossetti1  <3

**Comment by kingcons** [comment]
![problems](http://media.giphy.com/media/aAqGpWoSgGjnO/giphy.gif)

**Comment by brossetti1** [comment]
yeaheayh were fixing it :)

2015-02-20 9:57 GMT-05:00 Brit Butler notifications@github.com:

> trololololololol @brossetti1 https://github.com/brossetti1 <3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GroupOneCheckers/Checkers_RB/issues/17#issuecomment-75250758
> .

## 

with warm regards,

Brian Rossetti
415.527.6345
